name: Update Loto Data

on:
  schedule:
    - cron: "0 6 * * *"   # tous les jours à 6h
  workflow_dispatch:      # permet de lancer manuellement

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          pip install pandas numpy scikit-learn frenchlottery

      - name: Generate new data
        run: |
          cd data-pipeline
          python fetch_and_analyze.py

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Build site
        run: |
          cd frontend
          npm run build

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
